#%RAML 1.0 Library
usage:
traits:
  transactionid: !include traits/headerstrait.raml
  departurelocationcode: !include /libraries/common/traits/qparamsdeparturelocationcodetrait.raml  
  destinationlocationcode: !include /libraries/common/traits/qparamsdestinationlocationcodetrait.raml